### PR TITLE
refactor: add core modules to libp2p

### PR DESCRIPTION
**Pull request by jacobheun**
Resolves https://github.com/libp2p/js-libp2p/issues/384

### Modules
- [x] [js-libp2p-connection-manager](https://github.com/libp2p/js-libp2p-connection-manager)
- [x] [js-libp2p-identify](https://github.com/libp2p/js-libp2p-identify)
~~- [ ] [js-libp2p-keychain](https://github.com/libp2p/js-libp2p-keychain)~~
~~- [ ] [js-libp2p-nat-mngr](https://github.com/libp2p/js-libp2p-nat-mngr)~~
- [x] [js-libp2p-pnet](https://github.com/libp2p/js-libp2p-pnet)
- [x] [js-libp2p-ping](https://github.com/libp2p/js-libp2p-ping)
- [x] [js-libp2p-circuit](https://github.com/libp2p/js-libp2p-circuit)
- [x] ~~js-libp2p-switch~~ done via #388

### Cleanup
- [x] Consolidate tests
- [x] Consolidate util functions
- [x] Remove or minimize the package.json files of the merged repos
- [x] Clean up the READMEs

### Co-Authors

**Connection Mananger**
```
Co-authored-by: David Dias <daviddias.p@gmail.com>
Co-authored-by: Jacob Heun <jacobheun@gmail.com>
Co-authored-by: Pedro Teixeira <i@pgte.me>
Co-authored-by: Vasco Santos <vasco.santos@ua.pt>
```

**Identify**
```
Co-authored-by: David Dias <daviddias.p@gmail.com>
Co-authored-by: Friedel Ziegelmayer <dignifiedquire@gmail.com>
Co-authored-by: Hugo Dias <hugomrdias@gmail.com>
Co-authored-by: Jacob Heun <jacobheun@gmail.com>
Co-authored-by: Maciej Krüger <mkg20001@gmail.com>
Co-authored-by: Richard Littauer <richard.littauer@gmail.com>
Co-authored-by: Vasco Santos <vasco.santos@moxy.studio>
Co-authored-by: Yusef Napora <yusef@protocol.ai>
Co-authored-by: ᴠɪᴄᴛᴏʀ ʙᴊᴇʟᴋʜᴏʟᴍ <victorbjelkholm@gmail.com>
```

**Pnet**
```
Co-authored-by: Jacob Heun <jacobheun@gmail.com>
Co-authored-by: Vasco Santos <vasco.santos@moxy.studio>
```

**Ping**
```
Co-authored-by: David Dias <daviddias.p@gmail.com>
Co-authored-by: Francisco Baio Dias <xicombd@gmail.com>
Co-authored-by: Friedel Ziegelmayer <dignifiedquire@gmail.com>
Co-authored-by: Hugo Dias <mail@hugodias.me>
Co-authored-by: Jacob Heun <jacobheun@gmail.com>
Co-authored-by: João Antunes <j.goncalo.antunes@gmail.com>
Co-authored-by: Richard Littauer <richard.littauer@gmail.com>
Co-authored-by: Vasco Santos <vasco.santos@moxy.studio>
Co-authored-by: Vasco Santos <vasco.santos@ua.pt>
Co-authored-by: ᴠɪᴄᴛᴏʀ ʙᴊᴇʟᴋʜᴏʟᴍ <victorbjelkholm@gmail.com>
```

**Circuit**
```
Co-authored-by: David Dias <daviddias.p@gmail.com>
Co-authored-by: Dmitriy Ryajov <dryajov@gmail.com>
Co-authored-by: Friedel Ziegelmayer <dignifiedquire@gmail.com>
Co-authored-by: Hugo Dias <mail@hugodias.me>
Co-authored-by: Jacob Heun <jacobheun@gmail.com>
Co-authored-by: Jacob Heun <jake@andyet.net>
Co-authored-by: Maciej Krüger <mkg20001@gmail.com>
Co-authored-by: Oli Evans <oli@tableflip.io>
Co-authored-by: Pedro Teixeira <i@pgte.me>
Co-authored-by: Vasco Santos <vasco.santos@ua.pt>
Co-authored-by: Victor Bjelkholm <victorbjelkholm@gmail.com>
Co-authored-by: Yusef Napora <yusef@napora.org>
Co-authored-by: dirkmc <dirk@mccormick.cx>
```

### CODE REVIEW

**Comment by jacobheun** [comment]
I am postponing js-libp2p-keychain and js-libp2p-nat-mngr for subsequent PRs. Keychain is currently only used externally. It makes sense to pull this into js-libp2p, but this will be an API change, as we will likely move that under `libp2p.keychain`. As such, this should be done separately, imo.
Nat Manager isn't ready yet, so it doesn't make sense to pull it into master. That should be pulled in when it's initial iteration is ready for use.

I've done some test de duplication, but I am avoiding removing too much as part of this. I think it is safer and makes more sense to do the components as individual PRs, so that the changes are easier to follow. This could also be a good opportunity to clean up tests for each component as those pieces are migrated to async/await.

**Comment by daviddias** [comment]
This is really great work @jacobheun! Thank you so much for owning it ❤️

I see that the modules that have been merged, haven't gotten a deprecation notice and a redirect to this one instead. Also, the table should be updated https://github.com/libp2p/js-libp2p#packages

**Comment by jacobheun** [comment]
@daviddias yes! This is on my list to do this week, although I will likely need to have an org admin do some of this as archiving and description modifications are outside of my perms list. I'll put together a list of things that need to be done and hand off the pieces I need perms support for.

**Comment by daviddias** [comment]
I've went ahead and helped by moving all the outstanding issues to js-libp2p so that they are not lost (and updating the title so that it is easy to know where they came from). I've also disabled issues on those repos to avoid the creation of new ones.

Happy to do the Org Admin stuff once the PRs and deprecation notices (both in the repo and in npm) are done. Just ping me :)

**Comment by hugomrdias** [comment]
just wanted to say AWESOME WORK thank you 🙏

**Pull request merged**
