### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by diasdavid**
SPDY tests are failing

```
  1) stream muxing
       spdy only:
     Uncaught Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
      at doWrite (_stream_writable.js:406:19)
      at writeOrBuffer (_stream_writable.js:394:5)
      at Socket.Writable.write (_stream_writable.js:294:11)
      at /Users/imp/code/js-libp2p/node_modules/stream-to-pull-stream/index.js:78:30
      at /Users/imp/code/js-libp2p/node_modules/pull-stream/throughs/map.js:19:9
      at /Users/imp/code/js-libp2p/node_modules/pull-cat/index.js:35:13
      at /Users/imp/code/js-libp2p/node_modules/pull-cat/index.js:35:13
      at /Users/imp/code/js-libp2p/node_modules/pull-cat/index.js:35:13
      at read (node_modules/pull-length-prefixed/src/encode.js:49:7)
      at /Users/imp/code/js-libp2p/node_modules/pull-stream/throughs/async-map.js:39:20
      at mac.digest (node_modules/libp2p-secio/src/etm.js:25:11)
      at Immediate.setImmediate (node_modules/libp2p-secio/node_modules/libp2p-crypto/src/hmac/index.js:14:9)

```

### CODE REVIEW

**Comment by diasdavid** [comment]
everything else is fine.

**Comment by jacobheun** [comment]
I'm looking into spdy issues that popped up while testing the examples for the 0.24 release

**Comment by jacobheun** [comment]
Oddly, the issue only happens with the aegir upgrade to 17.0.1. Aegir 15.3.1 runs fine. I'm looking into the root issue as spdy is probably throwing errors it shouldn't be and the latest aegir is somehow exposing that.

**Comment by jacobheun** [comment]
So this issue is coming up because the setImmediate call in crypto, https://github.com/libp2p/js-libp2p-crypto/blob/master/src/hmac/index.js#L13, is causing a write to happen after the stream has been destroyed. 

As this issue is likely to pop up elsewhere with badly behaved streams, I created a PR in `stream-to-pull-stream` to check if the stream is writable before writing to it. https://github.com/pull-stream/stream-to-pull-stream/pull/14

**Comment by jacobheun** [comment]
Closing in favor of #279

**Pull request closed without merging**
