### PR TITLE
fix: abort connection only when abortConnectionOnPingFailure is true

### PR DESCRIPTION
**Pull request by sumitvekariya**
## Title

fix: abort connection only when abortConnectionOnPingFailure is true

## Description
https://github.com/libp2p/js-libp2p/issues/2678
This implementation does the following:
1. It checks if abortConnectionOnPingFailure is not explicitly set to false.
2. If it's not false (by default true), it aborts the connection.
3. If it's false, it logs a warning but doesn't abort the connection.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by achingbrain** [comment]
Thank you for opening this. Please can you add a test to prevent future regressions?

**Comment by sumitvekariya** [comment]
> Thank you for opening this. Please can you add a test to prevent future regressions?
test cases added

**Comment by maschad** [comment]
Thanks for taking this on @sumitvekariya , it seems like you have some [build errors](https://github.com/libp2p/js-libp2p/actions/runs/10742738805/job/29823386854?pr=2684) 

Please ensure you read through the `README.md` particularly the [development section](https://github.com/libp2p/js-libp2p/blob/main/README.md#development) before opening the PR for review so that the PR builds and tests pass before review.

**Comment by sumitvekariya** [comment]
> Thanks for taking this on @sumitvekariya , it seems like you have some [build errors](https://github.com/libp2p/js-libp2p/actions/runs/10742738805/job/29823386854?pr=2684)
> 
> Please ensure you read through the `README.md` particularly the [development section](https://github.com/libp2p/js-libp2p/blob/main/README.md#development) before opening the PR for review so that the PR builds and tests pass before review.

Hey, apologies, I missed the build errors, I have fixed the build errors, and tested locally, build is successful and all the test cases are passed as well

**Review by maschad — APPROVED** [review]

**Review by achingbrain — APPROVED** [review]

**Pull request merged**
