### PR TITLE
fix: event emitter and interfaces types for discovery and routing

### PR DESCRIPTION
**Pull request by vasco-santos**
~~Needs to have dist folder removed (testing with lodestar for now)~~

Tested with https://github.com/ChainSafe/lodestar/pull/2442 for last fixes. There is a `fix/event-emitter-types-with-local-types-dist` branch with the build commited to test in lodestar

Needs:
- [ ] https://github.com/pgte/moving-average/pull/11
- [x] https://github.com/libp2p/js-libp2p-interfaces/pull/95

### CODE REVIEW

**Comment by achingbrain** [comment]
`src/types.d.ts` is a new, empty file?  Was it added by mistake?

**Comment by vasco-santos** [comment]
> src/types.d.ts is a new, empty file? Was it added by mistake?

Yes, removing it now

**Review by achingbrain — APPROVED** [review]
LGTM, pending GH dep version removal

**Comment by vasco-santos** [comment]
shipped `moving-averages` on my npm namespace until we have a final release to unblock this

**Pull request merged**
