### PR TITLE
docs(readme): add package listing

### PR DESCRIPTION
**Pull request by dignifiedquire**
See https://github.com/ipfs/js-ipfs/pull/385 for details

### CODE REVIEW

**Comment by diasdavid** [comment]
Usage should be above Packages. Not sure about Contribute vs Packages (I vote for Contribute first)

**Comment by dignifiedquire** [comment]
I vote for Contribute second, as you first have to use it and understand things before you contribute. Also this does not follow standard readme, so maybe we can get @RichardLitt to work his magic?

**Comment by diasdavid** [comment]
standard-readme 👼 :D

**Comment by RichardLitt** [comment]
Will standardize this!

**Pull request merged**
