### PR TITLE
swapped dep to maintained package

### PR DESCRIPTION
**Pull request by TJKoury**
[Solves this issue.](https://github.com/libp2p/js-libp2p/issues/888)

Went with a different library ([es6-promisify](https://www.npmjs.com/package/es6-promisify)) since the package maintainer's solution (use Node's native [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original)) would require an additional shim for browser use.

### CODE REVIEW

**Comment by vasco-santos** [comment]
@TJKoury it seems that a release of `moving-average` module broke the build. I will check it out to unblock this

**Comment by TJKoury** [comment]
@vasco-santos Is there a task for running these typescript checks locally?

**Comment by TJKoury** [comment]
That’s strange, I’ve run the build task a few times but no errors.

**Comment by TJKoury** [comment]
Copy.  Let me get to where you are and I can help tackle the other issues.
I’ll be good to go after a few iterations here.

**Review by vasco-santos — APPROVED** [review]
LGTM

**Pull request merged**
