### PR TITLE
refactor: move error codes to @libp2p/interface/errors

### PR DESCRIPTION
**Pull request by wemeetagain**
## Description

- move `codes` from `libp2p/src/errors.js` to `@libp2p/interface/errors`
- from discussion of #2107, we decided that moving error codes should be done here in a separate PR

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by wemeetagain** [comment]
@maschad this is needed for #2107, which is a prereq for #2104

**Comment by maschad** [comment]
That's correct @wemeetagain , my apologies as I should clarify - we should resolve how we are going to synchronize all of the PRs which contain breaking changes such that they are all in released in v1 as opposed to any bug fix releases which we may need to do before v1.

We can discuss more on the Open Maintainers call on 10-10-2023

**Comment by achingbrain** [comment]
Is this actually breaking?  Do we export these error codes?

**Comment by wemeetagain** [comment]
> Is this actually breaking? Do we export these error codes?

I guess not. Still would like to target v1 branch tho

**Comment by wemeetagain** [comment]
closing this since we decided to move over error codes only one by one as needed.

**Pull request closed without merging**
