### PR TITLE
chore: remove webkit fixes

### PR DESCRIPTION
**Pull request by achingbrain**
To see if this is still broken in ci.

### CODE REVIEW

**Comment by achingbrain** [comment]
Can you hold off merging draft PRs in future please, this wasn’t done!

**Comment by maschad** [comment]
Sorry about that, will do.

**Comment by p-shahi** [comment]
General convention is to leave PR merges to the author, unless requested/special circumstance. I think we should follow that?

Can also think about enabling mergify which would allow us to add a `merge` or `ship-it` label )indicating a PR is ready) and let automation handle it

**Comment by maschad** [comment]
> General convention is to leave PR merges to the author, unless requested/special circumstance. I think we should follow that?

Agreed. This was an particular case since we where trying to reproduce a CI issue but will adhere to that going forward.

> Can also think about enabling mergify which would allow us to add a merge or ship-it label )indicating a PR is ready) and let automation handle it

Sounds like a good idea.

**Pull request merged**
