### PR TITLE
feat: circuit v2

### LINKED ISSUE #1029: Implement Circuit Relay v2 in JS
go-ipfs 0.11 will ship with circuits v2, js-ipfs should be able to talk to them. 

Ref. https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md

[Update 2023-01-05] In-progress PR:
https://github.com/libp2p/js-libp2p/pull/1533

https://github.com/libp2p/js-libp2p/issues/1029#tasklist-block-70c5c890-a1dc-436c-91b8-47f5543d0b27

### PR DESCRIPTION
**Pull request by mpetrunic**
closes #1029 
Implemented:
- hop protocol + unit tests
- stop protocol + unit tests
- integrated into transport with v1 fallback
- real reservation store
- sending reservations and maintaining relays
- reservation client - establishing reservations on relay

Open questions:
- ~~ what to use as storage for reservation store? ~~
- the best way to do periodic refreshing of reservations?
- is there a way for tagging connections as priority so they don't get removed?

~~At this point, `test/relay/relay.node.js` should pass but it doesn't. From my debugging, it breaks at upgrading connection but cannot figure out why (it hangs and then aborts) so I would appreciate somebody with more knowledge of how it works to take a look at it.~~ - fixed

### CODE REVIEW

**Comment by mpetrunic** [comment]
@achingbrain Could you help me with `test/dialing/resolver.spec.js` It seems like it's trying to use  libp2p from aegir.js as a relay but in circuiv2 it takes too long to create a reservation with that libp2p and test fails before that happens. Any ideas on how to fix/circumvent that.

I could easily fix it if I could get access to that libp2p variable as I could stub reservation before test starts.

**Comment by mpetrunic** [comment]
@achingbrain @wemeetagain finally got this in a working state. There is probably a lot of weird stuff as this PR has gone trough numerous merges with a lot of conflicts

**Comment by BigLep** [comment]
@mpetrunic @achingbrain : what are the next steps for getting this over the line?  Is it just about code review?

**Comment by mpetrunic** [comment]
This is still missing the ability to purge expired reservations but not sure how to architect this as I would need to figure out where to put the reservation store so that it became Startable.

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/js-libp2p/pull/1475

**Pull request closed without merging**
