### PR TITLE
fix: add ipv6Check regex for private address

### PR DESCRIPTION
**Pull request by marcus-pousette**
## Title

fix: add ipv6Check regex for private address

## Description

Solves #2623 

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by achingbrain** [comment]
Will this handle other types of IPv4-Mapped IPv6 addresses made from private ipv4 addresses?

E.g.

`10.0.0.1` -> `::FFFF:0a00:1` - should be detected as private
`142.250.74.238` -> `::FFFF:8efa:4aee` - should be detected as public

**Comment by marcus-pousette** [comment]
> Will this handle other types of IPv4-Mapped IPv6 addresses made from ipv4 addresses?
> 
> E.g.
> 
> `10.0.0.1` -> `::FFFF:0a00:1` - should be detected as private `142.250.74.238` -> `::FFFF:8efa:4aee` - should be detected as public

aaah yes, I realised that the pattern is not perhaps right given your explanation in the github issue

**Comment by marcus-pousette** [comment]
Hmm this was a bit tricky, it seems like the multiaddr function removes the leading zeros, so for the 

example 
::ffff:0a00:1

we actually match against
::ffff:a00:1

the same can be for 1 or many leading zeros, 

It feels like this regex problem should have been solved many times other by someone else already

**Comment by achingbrain** [comment]
Agreed, it doesn't sound like this should be a new problem..  Our version [comes from](https://github.com/libp2p/js-libp2p/pull/2362) the [private-ip](https://www.npmjs.com/package/private-ip) module, which hasn't seen an update to these patterns for years.

**Comment by marcus-pousette** [comment]
I did a little bit of a not-like looking regex now where I explicitly try to match against some local ones. It works but might not be ideal

**Comment by marcus-pousette** [comment]
> Agreed, it doesn't sound like this should be a new problem.. That said, our version [comes from](https://github.com/libp2p/js-libp2p/pull/2362) the [private-ip](https://www.npmjs.com/package/private-ip) module, which hasn't seen an update to these patterns for years.

this one might be right, but the problem is that toString() on a multiaddrs yield a format where leading 0s are removed which I guess does not work well with this pattern

**Review by achingbrain — CHANGES_REQUESTED** [review]
This is nearly there - I've suggested a few more test cases for public addresses - it's failing on the first address above the class B range - `172.32.0.1`, the others seem fine.

**Comment by marcus-pousette** [comment]
thanks for making the changes! did not have time to continue this week

**Comment by achingbrain** [comment]
No problem - I wanted to get it in the next release, thanks for finding the issue and opening the PR!

**Pull request merged**
