### PR TITLE
fix!: remove version number from webrtc signalling protocol 

### PR DESCRIPTION
**Pull request by maschad**
## Title

fix!: remove version number from webrtc signalling protocol

## Description

BREAKING CHANGE: I don't see a rationale for having a version number at the moment and the [spec](https://github.com/libp2p/specs/blob/master/webrtc/webrtc.md#signaling-protocol) doesn't recommend this.

Closes https://github.com/libp2p/js-libp2p/issues/2238 

## Notes & open questions

Should there be a reason to include a version number a discussion could be opened on the spec

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by achingbrain** [comment]
Granted the spec doesn't have a version number for the protocol so the addition of the version number seems to be a mistake, but this change will break compatibility with any deployed js-libp2p nodes.

Given that this is the only shipping implementation of WebRTC private to private, perhaps the simpler solution would be to add the version number [to the spec](https://github.com/libp2p/specs/blob/master/webrtc/webrtc.md#signaling-protocol)?

**Review by achingbrain — CHANGES_REQUESTED** [review]
I'd like to explore the idea that adding a version number to the spec may be a less disruptive change than removing it here.

This change will break compatibility with any currently deployed js-libp2p nodes.

**Comment by maschad** [comment]
> Granted the spec doesn't have a version number for the protocol so the addition of the version number here seems to be a mistake, but this change will break compatibility with any deployed js-libp2p nodes.
> 
> Given that this is the only shipping implementation of WebRTC private to private, perhaps the simpler solution would be to add the version number [to the spec](https://github.com/libp2p/specs/blob/master/webrtc/webrtc.md?rgh-link-date=2023-11-17T17%3A48%3A02Z#signaling-protocol)?

That's a valid point but despite this being a breaking change I don't think that we should introduce versioning at the spec level just because this implementation was mistakenly versioned. I would be interested to see what other parties think though so perhaps open a discussion on specs?

**Comment by achingbrain** [comment]
Plenty of our other specs have versions so I don't think it's a massive ask, plus they are useful for future proofing ourselves.

We need to value reducing disruption to users above our own wish to have everything just so.

**Comment by wemeetagain** [comment]
I think the version in a protocol string can be valuable and help provide a clear upgrade path.  Also tend to think of protocols without explicit versions as an implicit 1.0.
When inevitably things change, and a new protocol spec supercedes an old one, the version helps aid in backwards compatibility decisions and, more subjectively, how to understand the evolution of a protocol (ie from v1 to v2).

**Comment by maschad** [comment]
Closing in favour of https://github.com/libp2p/specs/pull/598

**Pull request closed without merging**
