### PR TITLE
Update example multiaddrs of boostrap nodes

### PR DESCRIPTION
**Pull request by mburns**
This updates the docs to point to new(er) bootstrap nodes. Infra would like to decouple how we announce bootstrap records so that the datacenter (`ams-1`, `lon-1`) is not strictly tied to a peer id (`QmSol...`).

These new examples are using servers on different continents, instead of both being EU-based.

### CODE REVIEW

**Review by vasco-santos — COMMENTED** [review]
Thanks for the PR @mburns 

I tried the browser example with the new addresses, but they are all failing: 

WebSocket connection to 'wss://bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

Is this blocked by https://github.com/protocol/bifrost-infra/pull/827 ?

**Comment by mburns** [comment]
Yay for redundancy.

```
$ ipfs swarm connect /dns4/bootstrap.libp2p.io/tcp/443/wss/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
connect QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa success
```

**Comment by vasco-santos** [comment]
I am able to dial using go-ipfs, but not in JS. The address is not being resolved.
While `wss://ams-1.bootstrap.libp2p.io:443/p2p/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd` (old bootstrap) resolves and connects, the same does not happen with `wss://bootstrap.libp2p.io:443/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN`.

I am getting on websockets:
```
message: 'getaddrinfo ENOTFOUND bootstrap.libp2p.io',
  error: Error: getaddrinfo ENOTFOUND bootstrap.libp2p.io
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'bootstrap.libp2p.io'
  }
```

@jacobheun any ideas?

**Comment by jacobheun** [comment]
> /dns4/bootstrap.libp2p.io/tcp/443/wss/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
> /dns4/bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN

@mburns @vasco-santos  these are bad addresses. It "works" in go-ipfs because it already knows good addresses for those peers due to `dnsaddr` TCP addr resolution on boot. There is no dns4 resolution for bootstrap.libp2p.io, only TXT records, so this will never resolve.

@vasco-santos we need to implement https://github.com/multiformats/js-multiaddr/issues/94#issuecomment-683812616.

The bootstrap addresses should ideally just be:
```
/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa
/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN
```

@mburns In order for the dnsaddr's to work we also need the TXT records to contain the `wss` addresses, can we add them? 

A temporary workaround would be to use the underlying subdomains:
- `/dns4/ewr-1.bootstrap.libp2p.io/tcp/443/wss/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa`
- `/dns4/sjc-1.bootstrap.libp2p.io/tcp/443/wss/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN`

This isn't great because we're still hardcoding the subdomain addresses but until we add `dnsaddr` resolution in JS **and** add wss addresses to the TXT records, we can't dynamically resolve this.

@vasco-santos let's sync up to get the dnsaddr resolution support done so we're no longer blocked there.

**Comment by vasco-santos** [comment]
Do we have any example on how the TXT records will look like?

**Comment by jacobheun** [comment]
> Do we have any example on how the TXT records will look like?

You can use dig to see the existing multiaddrs, `dig -t TXT _dnsaddr.bootstrap.libp2p.io`.

Or a curl from Cloudflare's service:
`curl -H 'accept: application/dns-json' 'https://cloudflare-dns.com/dns-query?name=_dnsaddr.bootstrap.libp2p.io&type=TXT'`

**Comment by vasco-santos** [comment]
Cool thanks! I was missing the `_dnsaddr` part. I could get it now

**Comment by mburns** [comment]
thanks for connecting those dots, @jacobheun 

`wss` (and `quic`) addresses are now being advertised for the Bootstrap nodes.

```
$ dig +short TXT _dnsaddr.bootstrap.libp2p.io | tail -n 1
"dnsaddr=/dnsaddr/sjc-2.bootstrap.libp2p.io/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
```
=>
```
$ dig +short TXT _dnsaddr.sjc-2.bootstrap.libp2p.io
"dnsaddr=/ip4/147.75.109.29/tcp/4001/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip4/147.75.109.29/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip4/147.75.109.29/udp/4001/quic/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/tcp/4001/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/udp/4001/quic/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
```

**Comment by jacobheun** [comment]
@mburns so one problematic thing we have to deal with for wss addresses is that we can't resolve the domain in the dnsaddr record, because we need it for SSL resolution.

`/ip4/147.75.109.29/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp` needs to be backed by an SSL certificate for the browser to resolve it so we actually need the `dns` address to return, because we have to pass the domain to the Websocket transport in order for it to resolve in browsers.

So I think it will need to look like:
```
$ dig +short TXT _dnsaddr.sjc-2.bootstrap.libp2p.io
"dnsaddr=/ip4/147.75.109.29/tcp/4001/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/dns4/sjc-2.bootstrap.libp2p.io/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip4/147.75.109.29/udp/4001/quic/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/tcp/4001/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/dns6/sjc-2.bootstrap.libp2p.io/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/udp/4001/quic/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
```

And we have to avoid resolving dns4/dns6 addresses on the JS side.

**Comment by mburns** [comment]
>So I think it will need to look like:

Great. I've pushed those changes:

```
$  dig +short TXT _dnsaddr.sjc-2.bootstrap.libp2p.io
"dnsaddr=/dns4/sjc-2.bootstrap.libp2p.io/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/dns6/sjc-2.bootstrap.libp2p.io/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip4/147.75.109.29/tcp/4001/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip4/147.75.109.29/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip4/147.75.109.29/udp/4001/quic/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/tcp/4001/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/tcp/443/wss/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
"dnsaddr=/ip6/2604:1380:1000:6000::5/udp/4001/quic/p2p/QmZa1sAxajnQjVM8WjWXoMbmPd7NsWhfKsPkErzpm9wGkp"
```

**Review by vasco-santos — APPROVED** [review]
LGTM! Merging this into #782 with the doh resolver

**Pull request merged**
