### PR TITLE
chore: fix close for ConnectionManager

### PR DESCRIPTION
**Pull request by samlior**
fix close for ConnectionManager

### CODE REVIEW

**Review by vasco-santos — CHANGES_REQUESTED** [review]
Thanks for fixing this. Can you add a test to avoid future regressions?
The CI failure is not related to this, I will see what is happening there

**Comment by samlior** [comment]
I think this is an obvious bug, no need to add a specific test.

**Comment by vasco-santos** [comment]
> I think this is an obvious bug, no need to add a specific test.

It is a bug, and a test will guarantee that if this code is changed it will not be created again. A simple test should be added [here](https://github.com/libp2p/js-libp2p/blob/master/test/connection-manager/index.node.js#L270) where a peer connects and than immediately after stopping, it should have no connections

**Comment by samlior** [comment]
The PR with master has been rebased, and tests have been added for ConnetionManager.

**Review by vasco-santos — APPROVED** [review]
LGTM! Thanks @samlior

**Pull request merged**
