### PR TITLE
test: Add WebKit to interop tester

### PR DESCRIPTION
**Pull request by MarcoPolo**

### CODE REVIEW

**Comment by maschad** [comment]
Nice @MarcoPolo I can see that you are currently [blocked by the addition of the webkit tests to webRTC](https://github.com/libp2p/js-libp2p-webrtc/actions/runs/5195525930/jobs/9368355276?pr=177#step:6:41) which is causing the [same error](https://github.com/libp2p/js-libp2p/actions/runs/5205283393/jobs/9390562117?pr=1799#step:7:1138) I am debugging it myself.

**Comment by MarcoPolo** [comment]
Great! Please ping me when you figure it out. Or let me know if you want to pair debug this. I'll pause this work until that's done.

**Comment by maschad** [comment]
This is currently blocked by the lack of support for the [RTCPeerConnection API](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection) on [WebkitGTK](https://base-art.net/Articles/webrtc-in-webkitgtk-and-wpe-status-updates-part-i/) as explained in [this comment](https://github.com/libp2p/js-libp2p-webrtc/pull/177)

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/js-libp2p/issues/1808

**Pull request closed without merging**
