### PR TITLE
refactor!: remove libp2p.keychain

### PR DESCRIPTION
**Pull request by wemeetagain**
## Description
- Remove keychain from the `Libp2p` interface and `Libp2pNode` implementation

During an in-person discussion, it was found that the keychain has limited use and value being bundled in libp2p.
The rationale is that libp2p should bundle with only functionality required to run its internal machinery related to managing connections, streams, protocols, etc.

The Keychain interface and implementation have NOT been removed, they've been kept. So, users of the Keychain can instantiate one in their application and continue using it.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by maschad — APPROVED** [review]
LGTM

**Comment by achingbrain** [comment]
Please hold off merging breaking changes until we resolve WebRTC stream closing

**Review by achingbrain — CHANGES_REQUESTED** [review]
LGTM.  I've targeted the v1 release branch - please can you add some copy to the migration guide to cover these breaking changes.

**Review by achingbrain — CHANGES_REQUESTED** [review]
Dismissed review by accident, just needs migration instructions to help people upgrade.

LGTM.  I've targeted the v1 release branch - please can you add some copy to the migration guide to cover these breaking changes.

**Review by maschad — APPROVED** [review]

**Pull request merged**
