### PR TITLE
fix:  ensure to check for Infinity in checkMaxLimit function

### PR DESCRIPTION
**Pull request by SgtPooki**
fixes https://github.com/libp2p/js-libp2p/issues/1665

### CODE REVIEW

**Review by maschad — APPROVED** [review]
Thanks!

**Comment by SgtPooki** [comment]
note @maschad that we could also change this to `!Number.isSafeNumber(value)` which would catch both NaN and Infinity, but tbh, we should be catching NaN elsewhere. I think the NaN displaying in #1665 is something with `@libp2p/logger` or `debug`

**Comment by maschad** [comment]
Agreed @SgtPooki I think this more explicit handling is more appropriate to see the flow of execution.

**Comment by achingbrain** [comment]
What's the problem this solves?

If the limit is `Infinity` and the check it `if (value > limit) {`, `value` will never be over `limit`.

**Comment by SgtPooki** [comment]
Mostly to tidy up the log.

I saw these errors as a red herring of something else, found out limit was set to infinity but the log confused me.

**Pull request merged**
