### PR TITLE
chore: upgrade aegir

### PR DESCRIPTION
**Pull request by maschad**
Following the conversation [here](https://github.com/libp2p/js-libp2p/pull/1505#issuecomment-1385249719) this will allow us to address https://github.com/libp2p/js-libp2p/pull/1505

### CODE REVIEW

**Comment by mpetrunic** [comment]
It appears that it needs to be bumped in libp2p-interop repo first^^

**Comment by maschad** [comment]
> It appears that it needs to be bumped in libp2p-interop repo first^^

Thanks @mpetrunic, turns out @achingbrain  had already addressed [this](https://github.com/libp2p/js-libp2p/pull/1505#issuecomment-1385246073) I must have overlooked the comment

**Comment by achingbrain** [comment]
https://github.com/libp2p/interop/pull/82 has been merged and released, now there are a couple of hundred tedious linting errors to tidy up.

I think we should try to get #1533 in first as fixing all the linting noise will cause many, many conflicts in that branch so let's pause on this for a few days.

**Comment by p-shahi** [comment]
This is unblocked now that #1533 has been merged @maschad

**Comment by maschad** [comment]
Thanks @p-shahi ,  it's ready to be reviewed now @achingbrain @mpetrunic

**Review by achingbrain — APPROVED** [review]
LGTM

**Pull request merged**
