### PR TITLE
refactor!: remove isStarted method from Startable

### PR DESCRIPTION
**Pull request by achingbrain**
## Description

We have an `isStarted` method on the `Startable` interface but we only really use it in tests. Our implementations tend to guard on being started twice so it just adds noise to every implementation.

BREAKING CHANGE: the `isStarted` method has been removed from the `Startable` interface

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by achingbrain** [comment]
Draft because some tests are failing.

**Review by wemeetagain — COMMENTED** [review]
I don't see where the method is removed from the interface

**Comment by achingbrain** [comment]
Looks like I didn't manage to push all the changes, oops.  Should be ok now.

**Review by wemeetagain — APPROVED** [review]
Does it need a migration note?

**Comment by achingbrain** [comment]
I don't *think* so because people by and large shouldn't be starting/stopping components behind libp2p's back?

**Pull request merged**
