### PR TITLE
fixes go-js echo / plaintext fails to send message #1110

### PR DESCRIPTION
**Pull request by gitaaron**
Ref. https://github.com/libp2p/js-libp2p/issues/1110

fix(go-js-interop): Data property of pubkey in Exchange was encoded as entire pubkey protobuf object; 
instead it should just be the marshaled content of the pubkey

docs(example): include insecure cmd line option so that other clients (ie/ Go) can use plaintext

docs(example): follow newline convention for end of message to interop with other clients (eg/ Go)

docs(example): create PeerId from base58String for remote listener so that it can easily be changed for other clients (eg/ Go)

fix(test): plaintext only handles RSA PeerId encryption for now

### CODE REVIEW

**Review by lidel — CHANGES_REQUESTED** [review]
@gitaaron  mind creating a separate plaintext example, and leave existing one as-is? :pray:

**Comment by gitaaron** [comment]
@lidel - I sure can!

Just a caveat that I don't think the current sample will work with the go plaintext sample as is (unless something has changed on the Go side since I looked at it last)

**Comment by gitaaron** [comment]
@lidel - I've created a new sample called 'echo-newline' and mentioned you can optionally pass in an  '-insecure' cmd line param in the README

BTW - I made it a cmd line param to be consistent with the GO echo sample

**Review by wemeetagain — APPROVED** [review]
LGTM thanks @gitaaron

**Comment by BigLep** [comment]
2022-03-22 conversation: 
1. We need to add the example test to the list of .yaml file
2. Run CI to make sure it passes
3. Merge

@wemeetagain will take this - thank you!

**Comment by gitaaron** [comment]
> 2022-03-22 conversation:
> 
> 1. We need to add the example test to the list of .yaml file
> 2. Run CI to make sure it passes
> 3. Merge
> 
> @wemeetagain will take this - thank you!

Thanks  @BigLep  and @wemeetagain  !

@BigLep - is 'adding the example test to the list of .yaml' something  I should have done before submitting the PR?

**Comment by wemeetagain** [comment]
This also needs porting to typescript

**Comment by gitaaron** [comment]
> This also needs porting to typescript

Thanks for the feedback - is there a typescript sample or test I can use as reference by any chance?

**Comment by wemeetagain** [comment]
Whoops, I misspoke here, its not typescript thats required, its just using the latest version of libp2p.
The big change is that libp2p and libp2p dependencies are now only using ESM exports.
Here's an example that uses the latest libp2p: https://github.com/libp2p/js-libp2p/blob/master/examples/transports/3.js

**Comment by gitaaron** [comment]
> Whoops, I misspoke here, its not typescript thats required, its just using the latest version of libp2p. The big change is that libp2p and libp2p dependencies are now only using ESM exports. Here's an example that uses the latest libp2p: https://github.com/libp2p/js-libp2p/blob/master/examples/transports/3.js

Sounds good, thanks!  I'll have a look at this.

**Comment by gitaaron** [comment]
Hi Steve,

Sorry for the delay.  I was having trouble testing out the sample I created
with libp2p-noise but I think I narrowed it down to an older version.

Is it alright if I give you an update over the coming week?  Hopefully I
can have it fixed by then or let you know I am stuck.

Thanks,
Aaron

**Comment by gitaaron** [comment]
@BigLep - just looking at this again - it seems that running the samples requires an `npm run build` to build libp2p otherwise I see the following error -
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/asurty/POpen/libp2p/workspace-js-libp2p/js-libp2p/examples/node_modules/libp2p/dist/src/index.js' imported from /Users/asurty/POpen/libp2p/workspace-js-libp2p/js-libp2p/examples/echo/src/libp2p.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:394:11)
    at moduleResolve (node:internal/modules/esm/resolve:944:10)
    at defaultResolve (node:internal/modules/esm/resolve:1041:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
 ```

If that is the case I can create  a new issue and submit a PR to update the README in the future?

Also  going to close this PR and  open a new one in the future with new commits since this has diverged significantly from master.

**Pull request closed without merging**
