### PR TITLE
chore: add yamux to all tests

### PR DESCRIPTION
**Pull request by achingbrain**
Wherever we support mplex, add yamux

### CODE REVIEW

**Comment by achingbrain** [comment]
@wemeetagain looks like there are some differences in behaviour between yamux and mplex, mostly around error codes?

**Comment by wemeetagain** [comment]
looks like that ERR_UNDER_READ is coming from multistream select. Will look into this later

**Comment by maschad** [comment]
I opened up https://github.com/libp2p/js-libp2p/pull/1579 in favour of this

**Comment by achingbrain** [comment]
Closing in favour of https://github.com/libp2p/js-libp2p/pull/1579

**Pull request closed without merging**
