### PR TITLE
chore: add error codes to dht and pubsub errors

### PR DESCRIPTION
**Pull request by vasco-santos**
Added error codes to the dht and pubsub errors, as well as replaced `setImmediate` by `nextTick`.

In the context of [ipfs/js-ipfs#1879](https://github.com/ipfs/js-ipfs/pull/1879)

### CODE REVIEW

**Comment by jacobheun** [comment]
It would be good to have the codes exported from a constants file so we don't risk miss typing them. Also, most of the nextTick logic could probably just have the anonymous function removed since it doesn't need any local references.
```js
nextTick(callback, errCode(new Error('DHT is not available'), 'ERR_DHT_DISABLED'))
```

**Comment by vasco-santos** [comment]
Thanks @jacobheun 

That should be fixed

**Comment by vasco-santos** [comment]
I added tests for all of those!

**Comment by jacobheun** [comment]
@vasco-santos it looks like linting needs to be fixed in the tests.

**Pull request merged**
