### PR TITLE
feat: add pending connections count to metrics

### PR DESCRIPTION
**Pull request by 2color**
## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by achingbrain** [comment]
Given that this value can change rapidly between scrapes, do you think this might be better off as a counter rather than a gauge?

It should probably also have the `_total` suffix - see [Metric and Label naming](https://prometheus.io/docs/practices/naming/)

**Comment by 2color** [comment]
Counters can't go down. So we can't use them here since pending requests can go both up and down. 

https://prometheus.io/docs/tutorials/understanding_metric_types/#counter

**Comment by achingbrain** [comment]
> Counters can't go down

This is true - but when graphing them, we can use a [rate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) function to show their change over time.  This way we don't miss spikes between scrapes.

**Comment by 2color** [comment]
>To pick between counter and gauge, there is a simple rule of thumb: if the value can go down, it is a gauge.
> Counters can only go up (and reset, such as when a process restarts). They are useful for accumulating the number of events, or the amount of something at each event. For example, the total number of HTTP requests, or the total number of bytes sent in HTTP requests. Raw counters are rarely useful. Use the rate() function to get the per-second rate at which they are increasing. https://prometheus.io/docs/practices/instrumentation/#counter-vs-gauge-summary-vs-histogram

If at `t(0)` we have `100` pending connections and at `t(1)` we have `80` pending connections, how can capture that? 

> This way we don't miss spikes between scrapes.

I think catching spikes is a matter of the scrape interval. We could add a counter to track the total incoming connections (prior to upgrade unlike `libp2p_connection_manager_connections` which only counts upgraded connections), but that would still not necessarily help catch spikes between scrapes.

**Comment by wemeetagain** [comment]
Are pending connections only inbound?

We could use a histogram or summary for the # of pending connections observed when a new inbound connection is triggered.

We can also have a histogram/summary to track time from pending to fully connected.

**Comment by achingbrain** [comment]
How about adding the pending connections count to the existing [inbound/outbound connections metric](https://github.com/libp2p/js-libp2p/blob/main/packages/libp2p/src/connection-manager/index.ts#L262-L265) as a label?  

Then it'd graph with those automatically which might make things easier to observe?  This is similar to the "inbound unnegotiated" and "outbound unnegotiated" stream metrics.

**Comment by wemeetagain** [comment]
> How about adding the pending connections count to the existing [inbound/outbound connections metric](https://github.com/libp2p/js-libp2p/blob/main/packages/libp2p/src/connection-manager/index.ts#L262-L265) as a label?

Sounds good to me from a consistency perspective.

**Review by 2color — COMMENTED** [review]
LGTM with the latest changes

**Pull request merged**
