### PR TITLE
docs: add lead maintainer to package table

### PR DESCRIPTION
**Pull request by hacdias**
Add Lead Maintainer to package table.

Ref.: https://github.com/ipfs-shipyard/package-table/issues/3

### CODE REVIEW

**Comment by diasdavid** [comment]
@jacobheun @vasco-santos can we see what's up with the missing Lead Maintainers? I was pretty sure we assigned one to every module with https://github.com/ipfs/pm/issues/600

**Comment by vasco-santos** [comment]
I know that there are a few missing, such as `libp2p-record`, as I have a PR for it, but there is no lead maintainer. Maybe @jacobheun and myself should divide the remaining ones among us.

**Comment by diasdavid** [comment]
Jenkins in Windows is panicking again @libp2p/dx

**Comment by diasdavid** [comment]
@vasco-santos please track that in a new issue to get solved. It would be good to have a Lead Maintainer assigned asap.

**Comment by jacobheun** [comment]
I've created #259 to track this. The original split of packages we did in June was indeed a subset of the core libp2p modules. We can discuss this week and get appropriate maintainers assigned.

**Comment by vasco-santos** [comment]
Yes! I will have a look on the remaining repos today

**Pull request merged**
