### PR TITLE
docs: update packages table

### LINKED ISSUE #259: Ensure all libp2p packages have lead maintainters
The current list of libp2p packages, https://github.com/libp2p/js-libp2p/blob/3226632d83e8684e32b00eeb398b21158b94586d/README.md#packages, is missing lead maintainers for many of the packages.  We need to ensure there is a lead maintainer in place to keep them well maintained.

Reference: https://github.com/libp2p/js-libp2p/pull/258

For posterity, once lead maintainer assignment is complete, ensure the table is complete for libp2p at https://github.com/ipfs/pm/issues/600#issuecomment-385674334

### PR DESCRIPTION
**Pull request by vasco-santos**
Updated `libp2p` packages:

- [x] [interface-connection](https://github.com/libp2p/interface-connection) - Jacob - [interface-connection#27](https://github.com/libp2p/interface-connection/pull/27)
- [x] [interface-transport](https://github.com/libp2p/interface-transport) - Jacob - [interface-transport#42](https://github.com/libp2p/interface-transport/pull/42)
- [x] [interface-stream-muxer](https://github.com/libp2p/interface-stream-muxer) - Jacob - [interface-stream-muxer#51](https://github.com/libp2p/interface-stream-muxer/pull/51)
- [x] [interface-peer-discovery](https://github.com/libp2p/interface-peer-discovery) - Vasco - [interface-peer-discovery#3](https://github.com/libp2p/interface-peer-discovery/pull/3)
- [x] [libp2p-rendezvous](https://github.com/libp2p/js-libp2p-rendezvous) - Vasco - [js-libp2p-rendezvous#4](https://github.com/libp2p/js-libp2p-rendezvous/pull/4)
- [ ] [libp2p-nat-mngr](https://github.com/libp2p/js-libp2p-nat-mngr) - Jacob
- [x] [interface-peer-routing](https://github.com/libp2p/interface-peer-routing) - Vasco - [https://github.com/libp2p/interface-peer-routing/pull/17](https://github.com/libp2p/interface-peer-routing/pull/17)
- [x] [interface-content-routing](https://github.com/libp2p/interface-content-routing) - Vasco - [interface-content-routing#1](https://github.com/libp2p/interface-content-routing/pull/1)
- [x] [interface-record-store](https://github.com/libp2p/interface-record-store) - Vasco - [interface-record-store#14](https://github.com/libp2p/interface-record-store/pull/14)
- [x] [libp2p-record](https://github.com/libp2p/js-libp2p-record) - Vasco - [js-libp2p-record#9](https://github.com/libp2p/js-libp2p-record/pull/9)
- [x] [libp2p-ping](https://github.com/libp2p/js-libp2p-ping) - Jacob - [libp2p-ping#72](https://github.com/libp2p/js-libp2p-ping/pull/72)

We need to have all the packages above updated to merge this PR.

Closes #259

### CODE REVIEW

**Comment by vasco-santos** [comment]
Regarding the not implemented packages:

- `libp2p-udp`
- `libp2p-udt`
- `p2pcat`

Should we remove them from the table?

And what about `libp2p-secio`?

**Comment by jacobheun** [comment]
`libp2p-secio` has a lead maintainer but since it hasn't been published to npm since the field was added it's registering as unavailable.  The lead maintainer won't show up until the package is published.

**Comment by diasdavid** [comment]
@jacobheun fixing that now by releasing a patch version with updated deps :)

**Comment by diasdavid** [comment]
> Regarding the not implemented packages:

@vasco-santos agreed, remove packages that are not implemented at all

**Comment by vasco-santos** [comment]
I removed the not implemented packages and updated the lead maintainer for `libp2p-secio`.

Now me and Jacob only need to create the PRs for the remaining repos

**Comment by vasco-santos** [comment]
For finishing this, me and @jacobheun do not have write access to the following repos:

[libp2p/interface-peer-discovery](https://github.com/libp2p/interface-peer-discovery)
[libp2p/interface-peer-routing](https://github.com/libp2p/interface-peer-routing)
[libp2p/interface-record-store](https://github.com/libp2p/interface-record-store)
[libp2p/interface-connection](https://github.com/libp2p/interface-connection)
[libp2p/interface-transport](https://github.com/libp2p/interface-transport)
[libp2p/interface-stream-muxer](https://github.com/libp2p/interface-stream-muxer)
[libp2p/js-libp2p-nat-mngr](https://github.com/libp2p/js-libp2p-nat-mngr)

The right teams probably weren't added to the repos.  @libp2p/dx can you make sure the right teams are added to this repo?

**Comment by diasdavid** [comment]
@vasco-santos just added the JavaScript team to all of them

**Comment by daviddias** [comment]
@vasco-santos This update should be done through https://github.com/libp2p/js-libp2p/blob/master/package-list.json vs. updating on the README directly

**Comment by daviddias** [comment]
@vasco-santos updated it for you :)

@jacobheun, @vasco-santos now that some many parts of the core pieces are integrated, I believe that we can collapse it even more by:

- Merging peer-id and peer-info into a peer module
- Bringing peer-book into js-libp2p, given that it is only used inside of it.

**Comment by vasco-santos** [comment]
Thanks @daviddias ! :D 

I am planning to work on the `peer-*` refactor as soon as I get into the Peer store v2 work

**Pull request merged**
