### PR TITLE
[WIP] feat: circuitv2

### PR DESCRIPTION
**Pull request by ckousik**
Continues the circuit v2 implementation from https://github.com/libp2p/js-libp2p/pull/1166 .

Interop testing:
- [x] manually tested this against the Go implementation using the examples/auto-relay dialer and listener scripts

### CODE REVIEW

**Comment by wemeetagain** [comment]
Thanks for picking up the branch.
Pretty big change, fairly reviewing requires digging deeper into the spec.
Perhaps we can ensure this feature is tested as part of the existing interop testing suite, will give us more confidence its working as intended.

**Comment by BigLep** [comment]
@ckousik: if there is anything to discuss verbally here, feel free to show up the the js-libp2p triage call on 2022-11-15.  Many of the js-libp2p implementers are there.

**Comment by ckousik** [comment]
@BigLep I seemed to have missed today's js triage call. I added the wrong event to my calendar. Currently, I'm picking up from where @mpetrunic left off and have added a simple procedure to clear stale reservations and merged in the latest changes from master into this branch. I have manually tested this against the Go implementation using the examples/auto-relay dialer and listener scripts and currently waiting for review. We need this implementation as a pre-requisite for browser-to-browser connections using the webrtc transport.

**Comment by ckousik** [comment]
@achingbrain Squashing all of the above comments is proving quite difficult. Also, the current code disables circuit v1 completely (ref: https://github.com/libp2p/js-libp2p/pull/1475/files#diff-22c4eb6dd642d67acce49c5271427768070be6c5ad11b1cc2a23a0b11fba04fcR160). I feel it might be faster to rewrite circuit-v2 from the current master branch.

**Comment by p-shahi** [comment]
@ckousik maybe we can discuss this with @achingbrain @mpetrunic and all during the next js-libp2p triage

**Comment by p-shahi** [comment]
closed in favor of https://github.com/libp2p/js-libp2p/pull/1533

**Pull request closed without merging**
